devsearch/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('projects/', include('projects.urls'), name='projects'),
    path('', include('users.urls')),
    
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    # all profiles
    path('', views.user_profiles, name='profiles'),
    # a single profile
    path('profile/<str:pk>/', views.user_profile, name='profile'),
    # login and register
    path('login', views.user_login, name='login'),
    # register
    path('register', views.user_register, name='register'),
    # logout
    path('logout', views.user_logout, name='logout'),
]

projects/models.py
import os
import uuid
from datetime import date

from django.db import models
from django.db.models.deletion import CASCADE
from users.models import Profile


def project_file(instance, filename):
    """Renames uploaded project image to

    Args:
        instance ([type]): came from models.ImageField
        filename ([type]): came from models.ImageField

    Returns:
        string: project/%Y/%m/%d/str__str.ext
    """
    ext = filename.split('.')[-1]
    filename = f'{instance.pk}__{uuid.uuid4().hex}.{ext}'
    dirname = os.path.join('projects', date.today().strftime("%Y/%m/%d"))
    return os.path.join(dirname, filename)


class Project(models.Model):
    id = models.UUIDField(default=uuid.uuid4,
                          primary_key=True, unique=True, editable=False)
    title = models.CharField(max_length=30)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(
        upload_to=project_file, default="default.jpg", null=True, blank=True)

    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    # if the tag class sits beneath the projects class (which it does) then
    # you have to wrap the class Tag in single quotes.
    # If the class sits above, the you can leave the single quotes.
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created_at = models.DateField(auto_now_add=True)
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.title


class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote')
    )
    id = models.UUIDField(default=uuid.uuid4,
                          primary_key=True, unique=True, editable=False)
    # owner
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return self.value


class Tag(models.Model):
    id = models.UUIDField(default=uuid.uuid4,
                          primary_key=True, unique=True, editable=False)
    name = models.CharField(max_length=200)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return self.name

users/models.py
import os
import uuid
from datetime import date

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver


def profile_pics(instance, filename):
    ext = filename.split('.')[-1]
    filename = f'{instance.pk}__{uuid.uuid4().hex}.{ext}'
    dirname = os.path.join('profiles', date.today().strftime("%Y/%m/%d"))
    return os.path.join(dirname, filename)


class Profile(models.Model):
    id = models.UUIDField(default=uuid.uuid4,
                          primary_key=True, unique=True, editable=False)
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    username = models.CharField(max_length=200, null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    short_intro = models.CharField(max_length=500, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    profile_image = models.ImageField(
        upload_to=profile_pics, default="profiles/user-default.png", null=True, blank=True)
    social_github = models.CharField(max_length=200, null=True, blank=True)
    social_youtube = models.CharField(max_length=200, null=True, blank=True)
    social_twitter = models.CharField(max_length=200, null=True, blank=True)
    social_linedin = models.CharField(max_length=200, null=True, blank=True)
    social_website = models.CharField(max_length=200, null=True, blank=True)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return str(self.user.username)


class Skill(models.Model):
    id = models.UUIDField(default=uuid.uuid4,
                          primary_key=True, unique=True, editable=False)
    owner = models.ForeignKey(
        Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return str(self.name)

users/forms.py
# from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name',  'email', 'username', 'password1', 'password2']
        labels = {'first_name': 'Name', }

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import redirect, render

from .models import Profile
from .forms import CustomUserCreationForm


def user_login(request):
    page = 'login'

    if request.user.is_authenticated:
        """If the user is alreday authenticated, he will be redirecter to the
        profiles page when he tries to open the login.html site manually"""
        return redirect('profiles')

    if request.method == 'POST':
        username = request.POST['username'].lower()
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'Username does not exist!')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('profiles')
        else:
            messages.error(request, 'Username or password is incorrect!')

    return render(request, 'users/login_register.html')


def user_logout(request):
    logout(request)
    messages.info(request, 'You are logged out!')
    return redirect('login')


def user_register(request):
    page = 'register'
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()

            messages.success(request, 'User account was created!')

            login(request, user)
        else:
            messages.error(request, 'Account could not be created!')

    context = {
        'page': page,
        'form': form,
    }
    return render(request, 'users/login_register.html', context)


def user_profiles(request):
    profiles = Profile.objects.all()
    context = {'profiles': profiles}
    return render(request, 'users/profiles.html', context)


def user_profile(request, pk):
    profile = Profile.objects.get(id=pk)
    top_skills = profile.skill_set.exclude(description__exact="")
    other_skills = profile.skill_set.filter(description="")
    context = {'profile': profile, 'top_skills': top_skills,
               'other_skills': other_skills}
    return render(request, 'users/profile.html', context)

templates/users/login_register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% if page == 'register' %}
<!-- Register -->
<h1>Register User</h1>
<form action="{% url 'register' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Register User">
</form>
<p>Already have an account <a href="{% url 'login' %}">Login</a></p>



<div class="auth">
    <div class="card">
      <div class="auth__header text-center">
        <a href="/">
          <img src="{% static 'img/icon.svg' %}" alt="icon" />
        </a>
        <h3>Account SignUp</h3>
        <p>Create a new developer account</p>
      </div>

      <form action="#" class="form auth__form">
        <!-- Input:Text -->
        <div class="form__field">
          <label for="formInput#text">Full Name: </label>
          <input
            class="input input--text"
            id="formInput#text"
            type="text"
            name="text"
            placeholder="e.g. Dennis Ivanov"
          />
        </div>

        <!-- Input:Email -->
        <div class="form__field">
          <label for="formInput#email">Email Address: </label>
          <input
            class="input input--email"
            id="formInput#email"
            type="email"
            name="email"
            placeholder="e.g. user@domain.com"
          />
        </div>

        <!-- Input:Password -->
        <div class="form__field">
          <label for="formInput#password">Password: </label>
          <input
            class="input input--password"
            id="formInput#passowrd"
            type="password"
            name="password"
            placeholder="••••••••"
          />
        </div>
        <!-- Input:Password -->
        <div class="form__field">
          <label for="formInput#confirm-password">Confirm Password: </label>
          <input
            class="input input--password"
            id="formInput#confirm-passowrd"
            type="password"
            name="confirm-password"
            placeholder="••••••••"
          />
        </div>
        <div class="auth__actions">
          <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
        </div>
      </form>
      <div class="auth__alternative">
        <p>Already have an Account?</p>
        <a href="login.html">Log In</a>
      </div>
    </div>
  </div>

{% else %}

<!-- Login -->
<div class="auth">
    <div class="card">
        <div class="auth__header text-center">
            <a href="/">
                <img src="{% static 'img/icon.svg' %}" alt="icon" />
            </a>
            <h3>Account Login</h3>
            <p>Hello Developer, Welcome Back!</p>
        </div>

        <form action="{% url 'login' %}" method="POST" class="form auth__form">
            {% csrf_token %}

            <!-- Input:Email -->
            <div class="form__field">
                <label for="formInput#text">Username: </label>
                <input class="input input--text" id="formInput#text" type="text" name="username" placeholder="Username">
            </div>

            <!-- Input:Password -->
            <div class="form__field">
                <label for="formInput#password">Password: </label>
                <input class="input input--password" id="formInput#passowrd" type="password" name="password"
                    placeholder="••••••••">
            </div>

            <!-- Submit button -->
            <div class="auth__actions">
                <input class="btn btn--sub btn--lg" type="submit" value="Login">
                <a href="forgetpassword.html">Forget Password?</a>
            </div>


        </form>

        <div class="auth__alternative">
            <p>Don't have an account <a href="{% url 'register' %}">Register</a></p>
        </div>

    </div>
</div>

{% endif %}

{% endblock content %}

templates/users/profile.html
{% extends 'base.html' %}

{% block content %}

<!-- Main Section -->
<main class="profile my-md">
  <div class="container">
    <div class="layout">
      <div class="column column--1of3">
        <div class="card text-center">
          <div class="card__body dev">
            <img class="avatar avatar--xl" src="{{profile.profile_image.url}}" />
            <h2 class="dev__name">{{profile.name}}</h2>
            <p class="dev__title">{{profile.short_intro}}</p>
            <p class="dev__location">Based in {{profile.location}}</p>
            <ul class="dev__social">
              {% if profile.social_github %}
              <li>
                <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
              </li>
              {% endif %}
              {% if profile.social_youtube %}
              <li>
                <a title="Youtube" href="{{profile.social_youtube}}" target="_blank"><i class="im im-youtube"></i></a>
              </li>
              {% endif %}
              {% if profile.social_twitter %}
              <li>
                <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="im im-twitter"></i></a>
              </li>
              {% endif %}
              {% if profile.social_linedin %}
              <li>
                <a title="LinkedIn" href="{{profile.social_linedin}}" target="_blank"><i class="im im-linkedin"></i></a>
              </li>
              {% endif %}
              {% if profile.social_website %}
              <li>
                <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i
                    class="im im-globe"></i></a>
              </li>
              {% endif %}
            </ul>
            <a href="{{profile.user.email}}" class="btn btn--sub btn--lg">Send Message </a>
          </div>
        </div>
      </div>
      <div class="column column--2of3">
        <div class="devInfo">
          <h3 class="devInfo__title">About Me</h3>
          <p class="devInfo__about">
            {{profile.bio}}
          </p>
        </div>
        <div class="devInfo">
          <h3 class="devInfo__title">Skills</h3>
          <div class="devInfo__skills">
            {% for skill in top_skills %}
            <div class="devSkill">
              <h4 class="devSkill__title">{{skill.name}}</h4>
              <p class="devSkill__info">{{skill.description}}</p>
            </div>
            {% endfor %}

            <h3 class="devInfo__subtitle">Other Skills</h3>
            <div class="devInfo__otherSkills">
              {% for skill in other_skills %}
              <span class="tag tag--pill tag--sub tag--lg">
                <small>{{skill.name}}</small>
              </span>
              {% endfor %}
            </div>

          </div>
        </div>
        <div class="devInfo">
          <h3 class="devInfo__title">Projects</h3>
          <div class="grid grid--two">
            {% for project in profile.project_set.all %}
            <div class="column">
              <div class="card project">
                <a href="{% url 'project' project.id %}" class="project">
                  {% if  project.featured_image %}
                  <img class="project__thumbnail" src="{{ project.featured_image.url }}" alt="project thumbnail" />
                  {% endif %}
                  <div class="card__body">
                    <h3 class="project__title">{{project.title}}</h3>
                    <p><a class="project__author" href="{% url 'profile' profile.id %}">{{project.owner.name}}</a></p>
                    <p class="project--rating">
                      <span style="font-weight: bold;">{{project.vote_ratio}}%</span> Postitive
                      Feedback ({{project.vote_total}} Vote{{project.vote_total|pluralize:"s"}})
                    </p>
                    <div class="project__tags">
                      {% for tag in project.tags.all %}
                      <span class="tag tag--pill tag--main">
                        <small>{{tag}}</small>
                      </span>
                      {% endfor %}
                    </div>
                  </div>
                </a>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

{% endblock content %}

templates/users/profiles.html
{% extends 'base.html' %}

{% block content %}


<!-- Main Section -->
<main class="home">
    <section class="hero-section text-center">
        <div class="container container--narrow">
            <div class="hero-section__box">
                <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
                <h2>FROM AROUND THE WORLD</h2>
            </div>

            <div class="hero-section__search">
                <form class="form" action="#" method="get">
                    <div class="form__field">
                        <label for="formInput#search">Search Developers </label>
                        <input class="input input--text" id="formInput#search" type="text" name="text"
                            placeholder="Search by developer name" />
                    </div>

                    <input class="btn btn--sub btn--lg" type="submit" value="Search" />
                </form>
            </div>
        </div>
    </section>

    <!-- Search Result: DevList -->
    <section class="devlist">
        <div class="container">
            <div class="grid grid--three">
                {% for profile in profiles %}
                <div class="column card">
                    <div class="dev">
                        <a href="{% url 'profile' profile.id %}" class="card__body">
                            <div class="dev__profile">
                                <img class="avatar avatar--md" src="{{profile.profile_image.url}}" alt="image" />
                                <div class="dev__meta">
                                    <h3>{{profile.name}}</h3>
                                    <h5>{{profile.short_intro}}</h5>
                                </div>
                            </div>
                            <p class="dev__info">
                                {{profile.bio|slice:"200"}}
                            </p>
                            <div class="dev__skills">
                                {% for skill in profile.skill_set.all|slice:"6" %}
                                <span class="tag tag--pill tag--main">
                                    <small>{{skill}}</small>
                                </span>
                                {% endfor %}
                            </div>
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>

</main>


{% endblock content %}